import java.awt.Container;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JFrame;


/*
 * AdminGroupFrame.java
 *
 * Created on Feb 9, 2011, 10:13:47 PM
 *
 * @author CJ
 */
public class AdminGroupFrame extends ClientGUI{

    private String server;
    private int port;

    /** Creates new form AdminGroupFrame */
    public AdminGroupFrame(JFrame parent, UserToken token, HashMap keys, GroupClient groupClient,
            String serverName, int portNum) {
        super(parent, token);
        parentFrame = parent;
        userToken = token;
        gClient = groupClient;
        server = serverName;
        port = portNum;
        fileKeys = keys;
        initComponents();

        //display groups on frame creation
        ArrayList<String> groupList = (ArrayList<String>) userToken.getGroups();
        String[] groupArray = new String[1024];
        groupArray = groupList.toArray(groupArray);
        groupListPane.setListData(groupArray);
        groupListPane.setSelectedIndex(0);

        //display users in 0th group on frame creation
        String groupName = (String) groupListPane.getSelectedValue();
        ArrayList<String> memberList = (ArrayList<String>) gClient.listMembers(groupName, userToken);
        String[] memberArray = new String[memberList.size()];
        memberArray = memberList.toArray(memberArray);
        userListPane.setListData(memberArray);
        userListPane.setSelectedIndex(0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        logOutButton = new javax.swing.JButton();
        upDownButton = new javax.swing.JButton();
        createGroupButton = new javax.swing.JButton();
        delGroupButton = new javax.swing.JButton();
        createUserButton = new javax.swing.JButton();
        delUserButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        userListPane = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        groupListPane = new javax.swing.JList();
        seeButton = new javax.swing.JButton();
        addUserButton = new javax.swing.JButton();
        remUserButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        changePwdButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Groups:");

        logOutButton.setText("Log Out");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        upDownButton.setText("Go to Upload/Download");
        upDownButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upDownButtonActionPerformed(evt);
            }
        });

        createGroupButton.setText("Create New Group");
        createGroupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createGroupButtonActionPerformed(evt);
            }
        });

        delGroupButton.setText("Delete Selected Group");
        delGroupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delGroupButtonActionPerformed(evt);
            }
        });

        createUserButton.setText("Create New User");
        createUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserButtonActionPerformed(evt);
            }
        });

        delUserButton.setText("Delete User");
        delUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delUserButtonActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(userListPane);

        jLabel2.setText("Users:");

        jLabel3.setText("(Select only one)");

        jScrollPane1.setViewportView(groupListPane);

        seeButton.setText("See Group's Users");
        seeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeButtonActionPerformed(evt);
            }
        });

        addUserButton.setText("Add User to Group");
        addUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserButtonActionPerformed(evt);
            }
        });

        remUserButton.setText("Remove User from Group");
        remUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remUserButtonActionPerformed(evt);
            }
        });

        refreshButton.setText("Refresh Groups");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        changePwdButton.setText("Change Password");
        changePwdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePwdButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(logOutButton)
                            .addComponent(seeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(refreshButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createGroupButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(createUserButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(addUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(changePwdButton, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(upDownButton, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(delUserButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(delGroupButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(remUserButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)))
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addUserButton)
                    .addComponent(remUserButton)
                    .addComponent(refreshButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logOutButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(delUserButton)
                            .addComponent(createUserButton)
                            .addComponent(seeButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(delGroupButton)
                            .addComponent(createGroupButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(upDownButton)
                            .addComponent(changePwdButton))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void delGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delGroupButtonActionPerformed
        String groupName = (String) groupListPane.getSelectedValue();
        boolean delSuccess = gClient.deleteGroup(groupName, userToken);
        if(delSuccess){
            System.out.println("Group " + groupName + " successfully deleted");
        }else{
            System.out.println("Failed to delete group, disconnecting");
            gClient.disconnect();
        }
    }//GEN-LAST:event_delGroupButtonActionPerformed

    private void upDownButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upDownButtonActionPerformed
        String username = userToken.getSubject();

        FileOpFrame csFrame = new FileOpFrame(parentFrame, userToken, fileKeys, gClient, server, port, username);
        Container csPane = csFrame.getContentPane();
        parentFrame.setContentPane(csPane);
        parentFrame.pack();
    }//GEN-LAST:event_upDownButtonActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        gClient.disconnect();

        ConFrame conFrame = new ConFrame(parentFrame, userToken);
        Container conPane = conFrame.getContentPane();
        parentFrame.setContentPane(conPane);
        parentFrame.pack();
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void createUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserButtonActionPerformed
        CreateUserFrame cuFrame = new CreateUserFrame(parentFrame, userToken, gClient);
        cuFrame.pack();
        cuFrame.setVisible(true);
    }//GEN-LAST:event_createUserButtonActionPerformed

    private void createGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createGroupButtonActionPerformed
        CreateGroupFrame cgFrame = new CreateGroupFrame(parentFrame, userToken, gClient);
        cgFrame.pack();
        cgFrame.setVisible(true);
    }//GEN-LAST:event_createGroupButtonActionPerformed

    private void delUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delUserButtonActionPerformed
        DelUserFrame delFrame = new DelUserFrame(parentFrame, userToken, gClient);
        delFrame.pack();
        delFrame.setVisible(true);
    }//GEN-LAST:event_delUserButtonActionPerformed

    private void seeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeButtonActionPerformed
        try{
            String groupName = (String) groupListPane.getSelectedValue();
            ArrayList<String> memberList = (ArrayList<String>) gClient.listMembers(groupName, userToken);
            String[] memberArray = new String[memberList.size()];
            memberArray = memberList.toArray(memberArray);
            userListPane.setListData(memberArray);
        }catch(NullPointerException e){
            System.err.println("No group selected.");
        }
    }//GEN-LAST:event_seeButtonActionPerformed

    private void addUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserButtonActionPerformed
        AddUtoGFrame augFrame = new AddUtoGFrame(parentFrame, userToken, gClient);
        augFrame.pack();
        augFrame.setVisible(true);
    }//GEN-LAST:event_addUserButtonActionPerformed

    private void remUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remUserButtonActionPerformed
        String selUser = (String) userListPane.getSelectedValue();
        String groupName = (String) groupListPane.getSelectedValue();

        boolean remSuccess = gClient.deleteUserFromGroup(selUser, groupName, userToken);
        if(remSuccess){
            System.out.println("Successfully removed " + selUser + " from " + groupName);
        }else{
            System.out.println("Failed to remove user, disconnecting.");
            gClient.disconnect();
        }
        
    }//GEN-LAST:event_remUserButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        ArrayList<String> groupList = (ArrayList<String>) gClient.listGroups(userToken);
        String[] groupArray = new String[groupList.size()];

        groupArray = groupList.toArray(groupArray);
        groupListPane.setListData(groupArray);
        groupListPane.setSelectedIndex(0);
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void changePwdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePwdButtonActionPerformed
        ChangePwdFrame cpFrame = new ChangePwdFrame(parentFrame, userToken, gClient);
        cpFrame.pack();
        cpFrame.setVisible(true);
    }//GEN-LAST:event_changePwdButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUserButton;
    private javax.swing.JButton changePwdButton;
    private javax.swing.JButton createGroupButton;
    private javax.swing.JButton createUserButton;
    private javax.swing.JButton delGroupButton;
    private javax.swing.JButton delUserButton;
    private javax.swing.JList groupListPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logOutButton;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton remUserButton;
    private javax.swing.JButton seeButton;
    private javax.swing.JButton upDownButton;
    private javax.swing.JList userListPane;
    // End of variables declaration//GEN-END:variables
}
