import java.awt.Container;
import java.util.HashMap;
import javax.swing.JFrame;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClientGUI.java
 *
 * Created on Feb 8, 2011, 4:10:16 PM
 */

/**
 *
 * @author CJ
 */
public class ClientGUI extends javax.swing.JFrame {

    protected JFrame parentFrame;
    protected UserToken userToken;
    protected GroupClient gClient;
    protected HashMap fileKeys;
    
    /** Creates new form ClientGUI */
    public ClientGUI(JFrame parent, UserToken token) {
        parentFrame = parent;
        userToken = token;
        initComponents();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("MainFrame"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ClientGUI mainWindow = new ClientGUI(null, null);
                mainWindow.setVisible(true);

                ConFrame conFrame = new ConFrame(mainWindow, null);
                Container conPane = conFrame.getContentPane();
                mainWindow.setContentPane(conPane);
                mainWindow.pack();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
