import java.awt.Container;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JFrame;

/*
 * UserGroupFrame.java
 *
 * Created on Feb 9, 2011, 10:24:19 PM
 *
 * @author CJ
 */
public class UserGroupFrame extends ClientGUI {

    private String server;
    private int port;

    /** Creates new form UserGroupFrame */
    public UserGroupFrame(JFrame parent, UserToken token, HashMap keys, GroupClient groupClient,
            String serverName, int portNum) {
        super(parent, token);
        parentFrame = parent;
        userToken = token;
        gClient = groupClient;
        server = serverName;
        port = portNum;
        fileKeys = keys;
        initComponents();

        //display groups on frame creation
        ArrayList<String> groupList = (ArrayList<String>) userToken.getGroups();
        String[] groupArray = new String[1024];
        groupArray = groupList.toArray(groupArray);
        groupListPane.setListData(groupArray);
        groupListPane.setSelectedIndex(0);

        //display users in 0th group on frame creation
        if(groupListPane.getSelectedValue() != null){
            String groupName = (String) groupListPane.getSelectedValue();
            ArrayList<String> memberList = (ArrayList<String>) gClient.listMembers(groupName, userToken);
            String[] memberArray = new String[memberList.size()];
            memberArray = memberList.toArray(memberArray);
            userListPane.setListData(memberArray);
        }
        userListPane.setSelectedIndex(0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        groupListPane = new javax.swing.JList();
        logOutButton = new javax.swing.JButton();
        createGroupButton = new javax.swing.JButton();
        remButton = new javax.swing.JButton();
        upDownButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        userListPane = new javax.swing.JList();
        seeButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        delGroupButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        changePwdButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Groups:");

        jScrollPane1.setViewportView(groupListPane);

        logOutButton.setText("Log Out");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        createGroupButton.setText("Create Group");
        createGroupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createGroupButtonActionPerformed(evt);
            }
        });

        remButton.setText("Remove User from Group");
        remButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remButtonActionPerformed(evt);
            }
        });

        upDownButton.setText("Go to Upload/Download");
        upDownButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upDownButtonActionPerformed(evt);
            }
        });

        addButton.setText("Add User to Group");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(userListPane);

        seeButton.setText("See Users");
        seeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("(Select only one)");

        jLabel2.setText("Users:");

        delGroupButton.setText("Delete Selected Group");
        delGroupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delGroupButtonActionPerformed(evt);
            }
        });

        refreshButton.setText("Refresh Groups");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        changePwdButton.setText("Change Password");
        changePwdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePwdButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(seeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(refreshButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(logOutButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(changePwdButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(delGroupButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(upDownButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(createGroupButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(remButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createGroupButton)
                    .addComponent(addButton)
                    .addComponent(refreshButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(remButton)
                    .addComponent(delGroupButton)
                    .addComponent(seeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logOutButton)
                    .addComponent(upDownButton)
                    .addComponent(changePwdButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void upDownButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upDownButtonActionPerformed
        String username = userToken.getSubject();

        gClient.connect(server, port);

        FileOpFrame csFrame = new FileOpFrame(parentFrame, userToken, fileKeys, gClient, server, port, username);
        Container csPane = csFrame.getContentPane();
        parentFrame.setContentPane(csPane);
        parentFrame.pack();
    }//GEN-LAST:event_upDownButtonActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        gClient.disconnect();

        ConFrame conFrame = new ConFrame(parentFrame, userToken);
        Container conPane = conFrame.getContentPane();
        parentFrame.setContentPane(conPane);
        parentFrame.pack();
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void createGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createGroupButtonActionPerformed
        UserCreateGroupFrame ucgFrame = new UserCreateGroupFrame(parentFrame, userToken, gClient);
        ucgFrame.pack();
        ucgFrame.setVisible(true);
    }//GEN-LAST:event_createGroupButtonActionPerformed

    private void remButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remButtonActionPerformed
        String username = (String) userListPane.getSelectedValue();
        String groupName = (String) groupListPane.getSelectedValue();

        boolean remSuccess = gClient.deleteUserFromGroup(username, groupName, userToken);
        if(remSuccess){
            System.out.println("Successfully removed " + username + " from " + groupName);
        }else{
            System.out.println("Failed to remove user, disconnecting");
            gClient.disconnect();
        }
    }//GEN-LAST:event_remButtonActionPerformed

    private void seeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeButtonActionPerformed
        String groupName = (String) groupListPane.getSelectedValue();
        ArrayList<String> memberList = (ArrayList<String>) gClient.listMembers(groupName, userToken);
        String[] memberArray = new String[memberList.size()];
        memberArray = memberList.toArray(memberArray);
        userListPane.setListData(memberArray);
    }//GEN-LAST:event_seeButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        AddUtoGFrame augFrame = new AddUtoGFrame(parentFrame, userToken, gClient);
        augFrame.pack();
        augFrame.setVisible(true);
    }//GEN-LAST:event_addButtonActionPerformed

    private void delGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delGroupButtonActionPerformed
        String groupName = (String) groupListPane.getSelectedValue();
        boolean delSuccess = gClient.deleteGroup(groupName, userToken);
        if(delSuccess){
            System.out.println("Group " + groupName + " successfully deleted");
        }else{
            System.out.println("Failed to delete group, disconnecting. ");
            gClient.disconnect();
        }
    }//GEN-LAST:event_delGroupButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        ArrayList<String> groupList = (ArrayList<String>) gClient.listGroups(userToken);
        String[] groupArray = new String[groupList.size()];

        groupArray = groupList.toArray(groupArray);
        groupListPane.setListData(groupArray);
        groupListPane.setSelectedIndex(0);
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void changePwdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePwdButtonActionPerformed
        ChangePwdFrame cpFrame = new ChangePwdFrame(parentFrame, userToken, gClient);
        cpFrame.pack();
        cpFrame.setVisible(true);
    }//GEN-LAST:event_changePwdButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton changePwdButton;
    private javax.swing.JButton createGroupButton;
    private javax.swing.JButton delGroupButton;
    private javax.swing.JList groupListPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logOutButton;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton remButton;
    private javax.swing.JButton seeButton;
    private javax.swing.JButton upDownButton;
    private javax.swing.JList userListPane;
    // End of variables declaration//GEN-END:variables

}
